name-template: '$NEXT_PATCH_VERSION 🎉'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'added'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'fixed'
  - title: '⚙️ Changes'
    labels:
      - 'changed'
      - 'dependencies'
  - title: '🧰 Removed'
    label: 'removed'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS_LIST

  ## Full Changelog
  [Full Changelog: $PREVIOUS_TAG...$CURRENT_TAG](https://github.com/$REPOSITORY/compare/$PREVIOUS_TAG...$CURRENT_TAG)
